# 1. NUMPY BASICS

In [1]:
# NumPy is a Linear Algebra Library used for multidimensional arrays
# NumPy brings the best of two worlds: (1) C/Fortran computational efficiency, (2) Python language easy syntax 
import numpy as np
# Let's define a one-dimensional array 
my_list = [10, 20, 50, 60, 70]
my_list


[10, 20, 50, 60, 70]

In [3]:
# Let's create a numpy array from the list "my_list"
x = np.array(my_list)
x

array([10, 20, 50, 60, 70])

In [4]:
type(x)

numpy.ndarray

In [5]:
# Multi-dimensional (Matrix definition) 
matrix = np.array( [ [5, 8], [9, 12]])
matrix

array([[ 5,  8],
       [ 9, 12]])

**MINI CHALLENGE #1:** 
- **Write a code that creates the following 2x4 numpy array**

```
[[4 6 8 7] 
[20 5 6 9]]
```

In [7]:
matrix4 = np.array( [ [4, 6, 8, 7], [20, 5, 6, 9] ] )
print(matrix4)

[[ 4  6  8  7]
 [20  5  6  9]]


# 2. BUILT-IN METHODS AND FUNCTIONS 

In [8]:
# "rand()" uniform distribution between 0 and 1
x = np.random.rand(15)
x

array([0.75789587, 0.08419082, 0.27168572, 0.70080546, 0.68932428,
       0.71106709, 0.70533689, 0.66142109, 0.69061016, 0.62824506,
       0.36893487, 0.31868598, 0.82623254, 0.75570512, 0.14389548])

In [9]:
# you can create a matrix of random number as well
x = np.random.rand(5, 5)
x

array([[0.62195318, 0.42415015, 0.46536079, 0.68688899, 0.10712414],
       [0.5601215 , 0.24424131, 0.15136729, 0.64471745, 0.30476012],
       [0.97829611, 0.29451848, 0.10372234, 0.55451632, 0.67084396],
       [0.56248361, 0.98967467, 0.4517154 , 0.88204164, 0.43079864],
       [0.05407513, 0.40067039, 0.48439544, 0.63630445, 0.60590813]])

In [10]:
# "randn()" normal distribution between 0 and 1
x = np.random.randn(10)
x


array([ 0.83613435,  0.06322491, -1.23762635, -1.09498333,  0.32534842,
       -0.83559836,  0.18252207, -2.90028847,  0.55405792, -1.44658009])

In [12]:
# "randint" is used to generate random integers between upper and lower bounds
x = np.random.randint(1, 10)
x

3

In [14]:
# "randint" can be used to generate a certain number of random itegers as follows
x = np.random.randint(1, 100, 15)
x

array([55, 64,  4,  4, 96, 83, 66, 23, 85, 82, 91,  5, 44, 47, 25])

In [15]:
# np.arange creates an evenly spaced values within a given interval
x = np.arange(1, 50)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [16]:
# Create an evenly spaced values with a step of 5
x = np.arange(1, 50, 5)
x

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46])

In [17]:
# create a diagonal of ones and zeros everywhere else
x = np.eye(15)
x

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.

In [18]:
# Array of ones
x = np.ones(10)
x

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [19]:
# Matrices of ones
x = np.ones((15, 15))
x

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.

In [20]:
# Array of zeros
x = np.zeros(20)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [21]:
x = np.zeros((10, 10))
x

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

**MINI CHALLENGE #2:**
- **Write a code that takes in a number x from the user and creates a 1x20 array with random numbers ranging from 0 to x**

In [23]:
x = int(input('Please enter a positive integer value: '))
arr = np.random.randint(0, x, 20)
arr

Please enter a positive integer value: 30


array([25, 22, 25,  0, 25, 26, 29, 17, 24, 26, 24,  4,  0, 16, 23, 15, 26,
        9, 13, 20])

# 3. SHAPE, LENGTH, TYPE, RESHAPE, AND MAX/MIN VALUES

In [30]:
# Let's define a one-dimensional array 
my_list = [-30, 4, 50, 70, 120, 17, 95, 8]
my_list

[-30, 4, 50, 70, 120, 17, 95, 8]

In [31]:
x = np.array(my_list)
x

array([-30,   4,  50,  70, 120,  17,  95,   8])

In [32]:
# Get Length of a numpy array
len(x)

8

In [33]:
# Get shape
x.shape

(8,)

In [29]:
# Obtain the datatype
x.dtype

dtype('int64')

In [34]:
# Reshape 1D array into a matrix
z = x.reshape(2, 4)
z

array([[-30,   4,  50,  70],
       [120,  17,  95,   8]])

In [36]:
# Obtain the maximum element (value)
x.max()

120

In [37]:
# Obtain the minimum element (value)
x.min()

-30

In [38]:
# Obtain the location of the max element
x.argmax()

4

In [39]:
# Obtain the location of the min element
x.argmin()

0

**MINI CHALLENGE #3:**
- **Write a code that creates a 4x5 array inwhich numbers range between 300 and 500 such that the difference between elements is 10**

In [41]:
x = np.arange(300, 500, 10)
z = x.reshape(4, 5)
z

array([[300, 310, 320, 330, 340],
       [350, 360, 370, 380, 390],
       [400, 410, 420, 430, 440],
       [450, 460, 470, 480, 490]])

**MINI CHALLENGE #4:**
- **Write a code that creates a 20x20 numpy array of random values that ranges from -1000 to 1000 and obtain the maximum, minimum, and mean values** 

In [49]:
x = np.random.randint(-1000, 1000, (20, 20))
x

array([[ 117, -476, -488, -988, -911,   35,  518,  641, -118,  156, -324,
        -440,  470, -339,  972, -220,  952,  785, -954,  388],
       [ 963,  503, -605, -233,  905, -356, -894, -594,  844, -723, -614,
         766, -617, -692, -360,  624, -443, -724,  303,  736],
       [ 444,  447,  539,  594, -862, -137,  708, -724,  840,   70, -774,
         320, -445, -479, -873,   18,  805,  203,  175,  326],
       [ 730, -620,  -86,  608, -169,  173, -508,  772,  463, -916, -936,
         689, -218, -325,   46, -997,  742,  432,  462, -951],
       [ 461,  577,  -93,  262,  778,  -35,  794, -759,  702, -341, -326,
          16, -205,   46,  299,  472, -286, -523,  350, -240],
       [ 596, -267,  578,  153,  626, -661,  678,  329, -541,  742, -494,
         465, -947,  712,  488, -246,  -91, -306,  302,  817],
       [-654,  756, -538,  861, -542,  437,  854,  375,   20,  229,  510,
        -497, -830,  129,  618, -992,  985, -822, -702, -123],
       [ 981,  135, -915, -657,  545,  90

In [50]:
x.shape

(20, 20)

In [51]:
x.max()

988

In [52]:
x.min()

-997

In [54]:
x.mean()

-6.22

In [55]:
print('The maximum value is: {} and the minimun value is: {}'.format(x.max(), x.min()))

The maximum value is: 988 and the minimun value is: -997


# 4. MATHEMATICAL OPERATIONS

In [56]:
# np.arange() returns an evenly spaced values within a given interval
x = np.arange(1, 10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
y = np.arange(1, 10)
y

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
# Add 2 numpy arrays together
sum = x + y
sum

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [59]:
squared = x**2
squared

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [60]:
sqrt = np.sqrt(squared)
sqrt

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [61]:
z = np.exp(y)
z

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

**MINI CHALLENGE #5:**
- **Given the X and Y values below, obtain the distance between them**


```
X = [3, 20, 30]
Y = [4, 6, 7]
```

The linear distance between the two points is the square root of the sum of the squared values of the x-axis distance and the y-axis distance.

d=√((x_2-x_1)²+(y_2-y_1)²)


In [65]:
# 1st
x = [3, 20, 30]
y = [4, 6, 7]
d = np.sqrt(np.square(y[0] - x[0]) + np.square(y[1] - x[1]) + np.square(y[2] - x[2]))
d

26.94438717061496

In [66]:
# 2d 
x = np.array([3, 20, 30])
y = np.array([4, 6, 7])
z = np.square(x - y)
print(z)

[  1 196 529]


In [68]:
dist = np.sqrt(np.sum(z))
dist

26.94438717061496

# 5. SLICING AND INDEXING 

In [76]:
x = np.array([20, 40, 50, 60, 70])
x

array([20, 40, 50, 60, 70])

In [77]:
# Access specific index from the numpy array
x[0]

20

In [78]:
# Starting from the first index 0 up until and NOT inlcluding the last element
x[0:4]

array([20, 40, 50, 60])

In [79]:
# Broadcasting, altering several values in a numpy array at once
x[0:2] = 10
x

array([10, 10, 50, 60, 70])

In [80]:
# Let's define a two dimensional numpy array
matrix = np.random.randint(1, 10, (5, 5))
matrix

array([[8, 4, 1, 3, 9],
       [8, 8, 8, 5, 9],
       [3, 3, 4, 4, 7],
       [3, 4, 8, 7, 9],
       [4, 8, 9, 4, 1]])

In [81]:
# Get a row from a matrix
matrix[0]

array([8, 4, 1, 3, 9])

In [83]:
matrix[4]

array([4, 8, 9, 4, 1])

In [84]:
# Get one element
matrix[0][0]

8

In [85]:
matrix[4][4]

1

In [86]:
matrix[2][2]

4

In [89]:
mini_matrix = matrix[:3]
mini_matrix

array([[8, 4, 1, 3, 9],
       [8, 8, 8, 5, 9],
       [3, 3, 4, 4, 7]])

In [91]:
mini_matrix2 = matrix[:, 2:]
mini_matrix2

array([[1, 3, 9],
       [8, 5, 9],
       [4, 4, 7],
       [8, 7, 9],
       [9, 4, 1]])

In [94]:
matrix

array([[8, 4, 1, 3, 9],
       [8, 8, 8, 5, 9],
       [3, 3, 4, 4, 7],
       [3, 4, 8, 7, 9],
       [4, 8, 9, 4, 1]])

In [95]:
mini_matrix3 = matrix[1:3, 1:3]
mini_matrix3

array([[8, 8],
       [3, 4]])

**MINI CHALLENGE #6:**
- **In the following matrix, replace the last row with -1**
- **Multiply the 2x2 matrix in the upper right corner by 2**



```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```



In [118]:
#x = np.array([2, 30, 20, -2, -4], [3, 4, 40, -3, -2], [-3, 4, -6, 90, 10], [25, 45, 34, 22, 12], [13, 24, 22, 32, 37])

# X = [2 30 20 -2 -4]
#     [3 4  40 -3 -2]
#     [-3 4 -6 90 10]
#     [25 45 34 22 12]
#     [13 24 22 32 37]

matrix = np.matrix('2 30 20 -2 -4; 3 4  40 -3 -2; -3 4 -6 90 10; 25 45 34 22 12; 13 24 22 32 37')
matrix

matrix([[ 2, 30, 20, -2, -4],
        [ 3,  4, 40, -3, -2],
        [-3,  4, -6, 90, 10],
        [25, 45, 34, 22, 12],
        [13, 24, 22, 32, 37]])

In [119]:
# matrix[4][:5] = -1

matrix[4] = -2
matrix

matrix([[ 2, 30, 20, -2, -4],
        [ 3,  4, 40, -3, -2],
        [-3,  4, -6, 90, 10],
        [25, 45, 34, 22, 12],
        [-2, -2, -2, -2, -2]])

In [116]:
matrix[:2, 3:5]*2

matrix([[-4, -8],
        [-6, -4]])

In [120]:
matrix[:2, 3:] = matrix[:2, 3:]*2
matrix

matrix([[ 2, 30, 20, -4, -8],
        [ 3,  4, 40, -6, -4],
        [-3,  4, -6, 90, 10],
        [25, 45, 34, 22, 12],
        [-2, -2, -2, -2, -2]])

# 6. ELEMENTS SELECTION (CONDITIONAL)

In [121]:
matrix = np.random.randint(1, 10, (5, 5))
matrix

array([[2, 2, 9, 3, 3],
       [3, 2, 5, 4, 7],
       [6, 2, 7, 7, 5],
       [1, 6, 5, 7, 1],
       [7, 1, 1, 8, 2]])

In [122]:
new_matrix = matrix[ matrix > 3 ]
new_matrix

array([9, 5, 4, 7, 6, 7, 7, 5, 6, 5, 7, 7, 8])

In [123]:
new_matrix = matrix[ matrix % 2 == 0 ]
new_matrix

array([2, 2, 2, 4, 6, 2, 6, 8, 2])

In [124]:
new_matrix = matrix[ matrix % 2 == 1 ]
new_matrix

array([9, 3, 3, 3, 5, 7, 7, 7, 5, 1, 5, 7, 1, 7, 1, 1])

**MINI CHALLENGE #7:**
- **In the following matrix, replace negative elements by 0 and replace odd elements with 25**


```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```


In [133]:
 x = np.matrix('2 30 20 -2 -4; 3 4  40 -3 -2; -3 4 -6 90 10; 25 45 34 22 12; 13 24 22 32 37')
 x

matrix([[ 2, 30, 20, -2, -4],
        [ 3,  4, 40, -3, -2],
        [-3,  4, -6, 90, 10],
        [25, 45, 34, 22, 12],
        [13, 24, 22, 32, 37]])

In [134]:
x[ x < 0 ] = 0
x

matrix([[ 2, 30, 20,  0,  0],
        [ 3,  4, 40,  0,  0],
        [ 0,  4,  0, 90, 10],
        [25, 45, 34, 22, 12],
        [13, 24, 22, 32, 37]])

In [135]:
x[ x % 2 == 1 ] = 25
x

matrix([[ 2, 30, 20,  0,  0],
        [25,  4, 40,  0,  0],
        [ 0,  4,  0, 90, 10],
        [25, 25, 34, 22, 12],
        [25, 24, 22, 32, 25]])

# EXCELLENT JOB!

# MINI CHALLENGES SOLUTIONS

**MINI CHALLENGE #1 SOLUTION:** 
- **Write a code that creates the following 2x4 numpy array**

```
[[4 6 8 7] 
[20 5 6 9]]
```

In [ ]:
x = np.array([[[4, 6, 8, 7] , [20, 5, 6, 9]]])
x

**MINI CHALLENGE #2 SOLUTION:**
- **Write a code that takes in a number x from the user and creates a 1x20 array with random numbers ranging from 0 to x**

In [ ]:
x = int(input("Please enter a positive integer value: "))
x = np.random.randint(1, x, 20)
x

**MINI CHALLENGE #3 SOLUTION:**
- **Write a code that creates a 4x5 array inwhich numbers ranging between 300 and 500 such that the difference between elements is 10**

In [ ]:
x = np.arange(300, 500, 10)
x.shape

In [ ]:
x = x.reshape(4, 5)
print(x)

**MINI CHALLENGE #4 SOLUTION:**
- **Write a code that creates a 20x20 numpy array of random values that ranges from -1000 to 1000 and obtain the maximum, minimum, and mean values** 

In [ ]:
x = np.random.randint(-1000, 1000, (20, 20))
print(x)
print('The maximum value is: {} and the minimum value is:{}'.format(x.min(), x.max()))

**MINI CHALLENGE #5 SOLUTION:**
- **Given the X and Y values below, obtain the distance between them**


```
X = [3, 20, 30]
Y = [4, 6, 7]
```




In [ ]:
X = np.array([3, 20, 30])
Y = np.array([4, 6, 7])
Z = np.sqrt(X**2 + Y**2)
Z

**MINI CHALLENGE #6 SOLUTION:**
- **In the following matrix, replace the last row with -1**
- **Multiply the 2x2 matrix in the upper right corner by 2**



```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```




In [ ]:
X = np.array([[2, 30, 20, -2, -4],
    [3, 4,  40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]])


In [ ]:
X[4] = 0
X

In [ ]:
X[:2, 3:]  = X[:2, 3:] * 2

In [ ]:
X

**MINI CHALLENGE #7 SOLUTION:**
- **In the following matrix, replace negative elements by 0 and replace odd elements with 25**


```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```


In [ ]:
X = np.array([[2, 30, 20, -2, -4],
    [3, 4,  40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]])

X[X%2==1] = 25
X[X<0] = 0
X